version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 10
    commands:
      - echo Installing angular cli...
      - npm install -g @angular/cli
      #- yarn add @angular-devkit/build-angular --dev
      - npm i @angular-devkit/build-angular@0.803.24
  build:
    commands:
      - echo Build started...
      - ng build --prod
artifacts:
  files:
    - dist/**/*