version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14.9.0
    commands:
      - echo Installing angular cli...
      - npm install
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
  build:
    commands:
      - echo Build started on `date`
      - ng build --prod
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - dist/**/*